first = input("Enter the first number: ")
second = input("Enter the second number: ")
first = int(first)
second = int(second)
print('\n')
print('Addition: ',first + second)
print('Subtraction: ',first - second)
print('Multiplication: ',first * second)
print('Division: ',first / second)